server:
  port: 8080
spring:
  application:
    name: demo1
  datasource:
    #数据库地址
    url: jdbc:mysql://localhost:3306/news?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    #数据账号
    username: root
    #数据密码
    password: root
