server:
  port: 8080
spring:
  application:
    name: demo1
  datasource:
    #数据库地址
    url: jdbc:mysql://localhost:3306/news?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    #数据账号
    username: root
    #数据密码
    password: root
    #mybatis的相关配置
mybatis:

  configuration:
    #开启驼峰命名法
    map-underscore-to-camel-case: true
    #mapper的xml 文件中使用别名时候的包名
  type-aliases-package: com.example.demo.entity
  #xml 文件 所在位置
  mapper-locations: classpath:mapper/*.xml